// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dossodmyeajjatngjufd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvc3NvZG15ZWFqamF0bmdqdWZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MTI3MjQsImV4cCI6MjA2ODI4ODcyNH0.WPgb1oJF4KNxfivMALN77G07v3bH8NfmSpjtAaejyIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);